start:
	node main.js

update:
	npm install

database:
	cd "C:\Program Files\MySQL\MySQL Server 8.0\bin"
	C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql -u root -p

checkInstall:
	if [ ! -d "~\Program Files\MySQL" ] then
		echo "The folder does not exist" 
	fi